#!/bin/bash

PASSWORD=`openssl passwd -1 password`

LOGFILE=/tmp/startup.log

echo "- START ------------" >> $LOGFILE
date +"%Y/%m/%d %H:%M:%S" >> $LOGFILE

function add_a_user {
  addgroup $1
  useradd -m -s /bin/bash -g $1 $1 -p $PASSWORD
  usermod -a -G $1 root
  su $1 -c "ssh-keygen -t rsa -P '' -f /home/$1/.ssh/id_rsa"
  su $1 -c "ssh-keygen -t dsa -P '' -f /home/$1/.ssh/id_dsa"
  su $1 -c "cat /home/$1/.ssh/id_rsa.pub >> /home/$1/.ssh/authorized_keys"
  su $1 -c "cat /home/$1/.ssh/id_dsa.pub >> /home/$1/.ssh/authorized_keys"
  su $1 -c "chmod 600 /home/$1/.ssh/authorized_keys"
  echo "Created user: $1" >> $LOGFILE
}

# Store the host key fingerprint to avoid a question when
# using SSH for the first time.
ssh-keyscan -t rsa,dsa localhost >> /etc/ssh/ssh_known_hosts

# Update the sysctl file to set swappiness. And set it for the current session.
wget -q http://www.affy.com/linode_build/sysctl.conf -O /etc/sysctl.conf
sysctl vm.swappiness=10

add_a_user accumulo
add_a_user hadoop
add_a_user zookeeper

echo "export DEFAULT_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games" >> /etc/profile.d/login_startup.sh
echo "export ACCUMULO_HOME=/usr/local/accumulo" >> /etc/profile.d/login_startup.sh
echo "export HADOOP_HOME=/usr/local/hadoop" >> /etc/profile.d/login_startup.sh
echo "export JAVA_HOME=/usr/lib/jvm/java-6-openjdk-i386" >> /etc/profile.d/login_startup.sh
echo "export ZOOKEEPER_HOME=/usr/local/zookeeper" >> /etc/profile.d/login_startup.sh
echo "export PATH=\$ACCUMULO_HOME/bin:\$HADOOP_HOME/bin:\$JAVA_HOME/bin:\$ZOOKEEPER_HOME/bin:\$DEFAULT_PATH" >> /etc/profile.d/login_startup.sh

echo "Created /etc/rc.local" >> $LOGFILE

apt-get -y install curl git maven2 openssh-server openssh-client openjdk-6-jdk subversion
echo "Installed packages" >> $LOGFILE

# Disable IP6
sudo echo "#disable ipv6" >> /etc/sysctl.conf
sudo echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
sudo echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
sudo echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf

# install and configure hadoop
cd /usr/local
wget -q http://www.affy.com/linode_build/hadoop-0.20.2.tar.gz
tar xvfz hadoop-0.20.2.tar.gz
rm hadoop-0.20.2.tar.gz
wget -q http://www.affy.com/linode_build/core-site.xml -O /usr/local/hadoop-0.20.2/conf/core-site.xml
wget -q http://www.affy.com/linode_build/hdfs-site.xml -O /usr/local/hadoop-0.20.2/conf/hdfs-site.xml
wget -q http://www.affy.com/linode_build/mapred-site.xml -O /usr/local/hadoop-0.20.2/conf/mapred-site.xml
wget -q http://www.affy.com/linode_build/hadoop-env.sh -O /usr/local/hadoop-0.20.2/conf/hadoop-env.sh
chown -R hadoop:hadoop /usr/local/hadoop-0.20.2
ln -s hadoop-0.20.2 hadoop

# Create the hadoop temp directory. It should not be in the /tmp directory because that directory
# disappears after each system restart. Something that is done a lot with virtual machines.
mkdir /hadoop_tmp_dir
chmod 777 /hadoop_tmp_dir
chown hadoop:hadoop /hadoop_tmp_dir

su hadoop -c "/usr/local/hadoop/bin/hadoop namenode -format"
# start hadoop
su hadoop -c "/usr/local/hadoop/bin/start-dfs.sh"
su hadoop -c "/usr/local/hadoop/bin/start-mapred.sh"

# install and configure zookeeper
cd /usr/local
wget -q http://www.affy.com/linode_build/zookeeper-3.4.3.tar.gz
tar xvfz zookeeper-3.4.3.tar.gz
rm zookeeper-3.4.3.tar.gz
wget -q http://www.affy.com/linode_build/zoo.cfg -O /usr/local/zookeeper-3.4.3/conf/zoo.cfg
chown -R zookeeper:zookeeper /usr/local/zookeeper-3.4.3
ln -s /usr/local/zookeeper-3.4.3 /usr/local/zookeeper
mkdir /zookeeper_tmp_dir
chmod 777 /zookeeper_tmp_dir
chown zookeeper:zookeeper /zookeeper_tmp_dir

# start zookeeper
su zookeeper -c "cd /usr/local/zookeeper; ./bin/zkServer.sh start"

# download, compile, configure accumulo
su hadoop -c "/usr/local/hadoop/bin/hadoop fs -mkdir /user/accumulo"
su hadoop -c "/usr/local/hadoop/bin/hadoop fs -chown accumulo /user/accumulo"
su accumulo -c "mkdir -p /home/accumulo/workspace/accumulo"
su accumulo -c "svn co https://svn.apache.org/repos/asf/accumulo/trunk /home/accumulo/workspace/accumulo"
echo "Cloned accumulo" >> $LOGFILE

su accumulo -c "cd /home/accumulo/workspace/accumulo; mvn -Dmaven.test.skip=true package -P assemble"
echo "Compiled accumulo" >> $LOGFILE

# Make the lib/ext directory group writeable so that you can deply jar files there.
cd /usr/local
tar xvfz /home/accumulo/workspace/accumulo/assemble/target/accumulo-1.5.0-SNAPSHOT-dist.tar.gz
mkdir /usr/local/accumulo-1.5.0-SNAPSHOT/lib/ext
mkdir /usr/local/accumulo-1.5.0-SNAPSHOT/logs
mkdir /usr/local/accumulo-1.5.0-SNAPSHOT/walogs
chmod g+w /usr/local/accumulo-1.5.0-SNAPSHOT/lib/ext
cp /usr/local/accumulo-1.5.0-SNAPSHOT/conf/examples/512MB/standalone/* /usr/local/accumulo-1.5.0-SNAPSHOT/conf
wget -q http://www.affy.com/linode_build/accumulo-site.xml -O /usr/local/accumulo-1.5.0-SNAPSHOT/conf/accumulo-site.xml
chown -R accumulo:accumulo /usr/local/accumulo-1.5.0-SNAPSHOT
ln -s /usr/local/accumulo-1.5.0-SNAPSHOT accumulo

#su accumulo -c "/usr/local/accumulo-1.5.0-SNAPSHOT/bin/accumulo init --clear-instance-name --instance-name instance --password secret"
#su accumulo -c "/usr/local/accumulo-1.5.0-SNAPSHOT/bin/start-all.sh"

date +"%Y/%m/%d %H:%M:%S" >> $LOGFILE
echo "- END ------------" >> $LOGFILE
