su hadoop -c "/usr/local/hadoop/bin/start-dfs.sh"
su hadoop -c "/usr/local/hadoop/bin/start-mapred.sh"
su zookeeper -c "cd /usr/local/zookeeper; ./bin/zkServer.sh start"
su hadoop -c "cd /usr/local/hadoop; ./bin/hadoop dfsadmin -safemode leave"
su accumulo -c "/usr/local/accumulo/bin/start-all.sh"
